"""Migração inicial

Revision ID: f3baf6693226
Revises: 
Create Date: 2023-08-18 17:01:56.444376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3baf6693226'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paroquia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.execute("INSERT INTO usuario (username, senha, nome, papel) VALUES ('master@test.com', 'pbkdf2:sha256:260000$MHeLL0ROwxQD6VqR$68a8934acb805c942a2c8e10ee5b3abcc94976ca577de5db66d05ca84c685724', 'Master', 'ADMIN')")
    op.create_table('movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id_paroquia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_paroquia'], ['paroquia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('apelido', sa.String(), nullable=False),
    sa.Column('id_paroquia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_paroquia'], ['paroquia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encontro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_termino', sa.Date(), nullable=False),
    sa.Column('id_movimento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_movimento'], ['movimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('id_movimento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_movimento'], ['movimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_esposo', sa.Integer(), nullable=True),
    sa.Column('id_esposa', sa.Integer(), nullable=True),
    sa.Column('id_paroquia', sa.Integer(), nullable=True),
    sa.Column('extenso', sa.String(), nullable=True),
    sa.Column('id_inscrito', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_esposa'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['id_esposo'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['id_inscrito'], ['encontro.id'], ),
    sa.ForeignKeyConstraint(['id_paroquia'], ['paroquia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cor', sa.String(), nullable=False),
    sa.Column('id_coordenador', sa.Integer(), nullable=True),
    sa.Column('id_encontro', sa.Integer(), nullable=True),
    sa.Column('id_paroquia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_coordenador'], ['casal.id'], ),
    sa.ForeignKeyConstraint(['id_encontro'], ['encontro.id'], ),
    sa.ForeignKeyConstraint(['id_paroquia'], ['paroquia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circulo')
    op.drop_table('casal')
    op.drop_table('equipe')
    op.drop_table('encontro')
    op.drop_table('pessoa')
    op.drop_table('movimento')
    op.drop_table('usuario')
    op.drop_table('paroquia')
    # ### end Alembic commands ###
