"""Nova atualização

Revision ID: 08ea9bdf0526
Revises: f2e0f967b55b
Create Date: 2023-09-08 15:51:29.841752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ea9bdf0526'
down_revision = 'f2e0f967b55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casal', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'circulo', ['id_circulo'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
