name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Restart Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          script: |
            sudo systemctl stop paroquial
            cd /home/ubuntu/gestorencontros
            git fetch origin
            poetry install
            FLASK_APP=encontros flask db upgrade
            sudo systemctl start paroquial
           
